language: python

matrix:
  include:
    # Use the built in venv for linux builds
    - os: linux
      sudo: required
      python: "3.8.6"
      dist: xenial

install:
  - python3 --version
  - python3 -m pip install -U pip

script:
  # NOTE
  # venv doesn't quite work - neewd to keep "activating" the next venv rather than deactivate first...

  #
  # --------------- localhost tests ---------------
  #
  - echo -en "travis_fold:start:testing_localhost_chrono_lens\\r"
  - echo "Testing localhost chrono_lens"
  - echo
  - python3 -m venv localhost-venv
  - source localhost-venv/bin/activate

  # command to install dependencies
  - pip install --use-feature=2020-resolver --quiet -r requirements-localhost.txt
  # includes extra 'test' specific dependencies
  - pip3 install --use-feature=2020-resolver --quiet -r tests/requirements.txt
  # for codecov support
  - pip3 install --use-feature=2020-resolver --quiet pytest==4.3.1 pytest-cov==2.9.0
  # to report installed packages
  - pip3 freeze
  # command to run tests
  - PYTHONPATH=. pytest --cov-config .coveragerc --cov=./ tests/
  - echo -en "travis_fold:end:testing_localhost_chrono_lens\\r"
  - echo "done"


  #
  # --------------- gcloud chrono_lens tests ---------------
  #
  - echo -en "travis_fold:start:testing_gcloud_chrono_lens\\r"
  - echo "Testing gcloud chrono_lens"
  - echo
  - python3 -m venv gcloud-venv
  - source gcloud-venv/bin/activate

  - which python3
  - which pip3
  - pip3 -V

  # command to install dependencies
  - pip3 install --use-feature=2020-resolver --quiet -r requirements-gcloud.txt
  # includes extra 'test' specific dependencies
  - pip3 install --use-feature=2020-resolver --quiet -r tests/requirements.txt
  - pip3 install --use-feature=2020-resolver --quiet -r tests/chrono_lens/gcloud/requirements.txt
  # for codecov support
  - pip3 install --use-feature=2020-resolver --quiet pytest==4.3.1 pytest-cov==2.9.0
  # to report installed packages
  - pip3 freeze
  # command to run tests
  - cd tests
  - PYTHONPATH=.. pytest --cov-config ../.coveragerc --cov=../ ./
  - cd ..
  # Pretend we're running on GCP
  - GCP_PROJECT="Travis" BUILD_ID="Travis" PYTHONPATH=. pytest --cov-config .coveragerc --cov=./ tests/
  - echo -en "travis_fold:end:testing_gcloud_chrono_lens\\r"
  - echo "done"


  #
  # --------------- gcloud cloud function tests ---------------
  #

  - cd cloud/functions

  # Find all subfolders with src, as these are the folders with GCP function code and create ci/cd triggers
  - |
    for repo_dir in **/src/
    do
      FUNCTION_NAME=${repo_dir%/*/} # get only base dir name e.g. distribute_json_sources/src/ -> distribute_json_sources
      echo -en "travis_fold:start:testing_${FUNCTION_NAME}\\r"
      echo "Testing cloud function <${FUNCTION_NAME}> locally"
      echo
      python3 -m venv ${FUNCTION_NAME}-venv
      source ${FUNCTION_NAME}-venv/bin/activate
      cd ${FUNCTION_NAME}
      echo "Copying root 'chrono_lens' folder as subdir to 'src' to enable local reuse of shared folder"
      cp -r ../../../chrono_lens src/
      pip3 install --use-feature=2020-resolver --quiet pytest==4.3.1 pytest-cov==2.9.0
      pip3 install --use-feature=2020-resolver --quiet -r src/requirements.txt
      if [ -f "tests/requirements.txt" ]; then pip3 install --use-feature=2020-resolver --quiet -r tests/requirements.txt; fi
      cd src
      echo "GCP_PROJECT='Travis' BUILD_ID='Travis' python -m pytest -v ../tests"
      GCP_PROJECT="Travis" BUILD_ID="Travis" python -m pytest -v ../tests
      cd ../..
      echo -en "travis_fold:end:testing_${FUNCTION_NAME}\\r"
      echo "done"
    done

after_success:
  - bash <(curl -s https://codecov.io/bash)
