import os

CONFIG_FOLDER = os.path.join('localhost', 'config')
DOWNLOAD_FOLDER = os.path.join('localhost', 'data')
COUNTS_FOLDER = os.path.join('localhost', 'counts')
MAXIMUM_NUMBER_OF_DOWNLOAD_ATTEMPTS = 5
DOWNLOAD_RETRY_SLEEP_MINIMUM = 5
DOWNLOAD_RETRY_SLEEP_MAXIMUM = 15
DEFAULT_LOG_LEVEL = 'INFO'
DEFAULT_IMAGES_MAXIMUM_DAYS_TO_RETAIN = 28
